sample_rate: 16000
highpass_cutoff: 50
num_examples: 5000 #300_000
min_mic_speaker_distance: 0.5
max_mic_speaker_distance: 4
min_wall_distance: 0.5
librispeech_path: /dsi/gannot-lab/gannot-lab1/datasets/LibriSpeech/LibriSpeech
mode: Test
save_dir: /dsi/gannot-lab/gannot-lab1/datasets/reverb_data/Test_complete/audio_final
audio_len: 5 # in sec

rt60_min: 0.2
rt60_max: 0.6

# room parameters
min_w: 4.5
max_w: 6.5
min_l: 4.5
max_l: 6.5
min_h: 2.5
max_h: 3
