
melgen:
  _name_: melgen
  in_channels: 80
  out_channels: 80
  diffusion_step_embed_dim_in: 128
  diffusion_step_embed_dim_mid: 512
  diffusion_step_embed_dim_out: 512
  res_channels: 512
  skip_channels: 512
  num_res_layers: 12
  dilation_cycle: 1
  mel_upsample: [2, 2]
  cond_feat_size: 80

diffusion:
  T: 400
  beta_0: 0.0001
  beta_T: 0.02
  beta: null

dataset:
  base_data_dir: /dsi/gannot-lab1/datasets/reverb_data/
  sampling_rate: ${audio.sampling_rate}
  min_block_size: 35 
  max_block_size: 65 
  min_spacing: 30
  audio_stft_hop: ${audio.hop_length}
  num4empty_str: 0 #or -12, 0, min

audio:
  sampling_rate: 16000
  filter_length: 640
  hop_length: 160
  win_length: 640
  mel_fmin: 20.0
  mel_fmax: 8000.0

train: # Not used in generate.py
  name: LibSp_only-conv1d-condition_fixed-mask      # Name of experiment (prefix of experiment name)
  save_dir: /dsi/gannot-lab1/users/mordehay/speech_repainting    # where checkpoints will be saved
  ckpt_iter: max    # continue training from a specific iteration
  # for testing the training phase
  # iters_per_ckpt: 20 #20 #10000
  # iters_per_logging: 1 #1 #100
  # n_iters: 200 #200 #1000001
  #for complete training
  iters_per_ckpt: 10000 #20 #10000
  iters_per_logging: 100 #1 #100
  n_iters: 2000001 #200 #1000001
  learning_rate: 2e-4
  batch_size_per_gpu: 128
  w_masked_pix: 0.7

generate:
  name: LibSp_only-conv1d-condition
  ckpt_path: /dsi/gannot-lab1/users/mordehay/speech_repainting/exp/LibSp_only-conv1d-condition/wnet_h512_d12_T400_betaT0.02/checkpoint/80000.pkl          
  n_samples: 3          # Number of utterances from test dataset to be generated, used in train every iters_per_ckpt iters
  n_samples_test: 20 # used in full inference mel only
  video_path: null      # generate audio for a given silent video file
  w_mel_cond: 2            # w1 in the paper
  w_asr: 0 #1.5            # w2 in the paper
  asr_start: 270        # t_asr
  save_dir: /dsi/gannot-lab1/users/mordehay/speech_repainting/exp/LibSp_only-conv1d-condition/wnet_h512_d12_T400_betaT0.02        # where to save the generated audio
  lipread_text_dir: null # directory with predicted text for generating test samples of benchmark dataset 

distributed:
  dist_backend: nccl
  dist_url: tcp://localhost:54321 #54321
